version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cert
      POSTGRES_PASSWORD: cert
      POSTGRES_DB: certdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://cert:cert@db:5432/certdb
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:



